data:
  root_dir: artifacts/data
  source_URL: https://drive.google.com/file/d/19nyK54FijEPS4Vq9QHzJfpjpbQDhd_Y6/view?usp=sharing
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  data_path: artifacts/Train.csv

  feature_store : "artifacts/data_ingestion/feature_store/data.csv"
  TRAIN_TEST_SPLIT_RATIO: 0.25
  FILE_NAME : "artifacts/data_ingestion/feature_store/data.csv"
  TRAIN_FILE_NAME: "artifacts/data_ingestion/ingested/train.csv"
  TEST_FILE_NAME: "artifacts/data_ingestion/ingested/test.csv"


processed_data_path: "artifacts/processed_data.csv"
model: "app/model.pkl"


# For MongoDB connection
DATABASE_NAME : "Proj1"
COLLECTION_NAME : "Proj1-Data"
MONGODB_URL_KEY : "MONGODB_URL"
