data:
  root_dir: artifacts/data
  source_URL: https://drive.google.com/file/d/1Q6LEJGK_TVtkB9vlw6eASOND1lzRh3RX/view?usp=sharing
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  data_path: artifacts/Train.csv

processed_data_path: "artifacts/processed_data.csv"
model: "app/model.pkl"
