enable_cache: False
extra:
  tags: zenml-projects
settings:
  docker:
    required_integrations:
      - mlflow
steps:
  model_train:
    experiment_tracker: mlflow_tracker
  evaluation:
    experiment_tracker: mlflow_tracker

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source_URL: https://drive.google.com/file/d/1fOCZ4t0t4lyXzn39vAEXTKSKaNTJs9Rl/view?usp=sharing
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  gurgaon_flats_data_path: artifacts/gurgaon_data/flats.csv
  gurgaon_appartments_data_path: artifacts/gurgaon_data/appartments.csv
  gurgaon_houses_data_path: artifacts/gurgaon_data/houses.csv

data_cleaning:
  cleaned_data_dir: artifacts/cleaned_data
  cleaned_gurgaon_data_path: artifacts/cleaned_data/gurgaon_data.csv
  missing_value_imputed: artifacts/cleaned_data/missing_value_imputed.csv
  gurgaon_data_path: artifacts/gurgaon_data/gurgaon_properties.csv
  gurgaon_flats_data_path: artifacts/gurgaon_data/flats.csv
  gurgaon_appartments_data_path: artifacts/gurgaon_data/appartments.csv
  gurgaon_houses_data_path: artifacts/gurgaon_data/houses.csv

data_visualization:
  viz_dir: artifacts/model
  feature_text: artifacts/model/feature_text.pkl
  data_viz: artifacts/model/data_viz1.csv
  missing_value_imputed: artifacts/cleaned_data/missing_value_imputed.csv
  latlong_data: artifacts/gurgaon_data/latlong.csv
  gurgaon_properties: artifacts/gurgaon_data/gurgaon_properties.csv

recommend_sys:
  recommend_dir: artifacts/model
  cosine1: artifacts/model/cosine_sim1
  cosine2: artifacts/model/cosine_sim2
  cosine3: artifacts/model/cosine_sim3
  appartments_path: artifacts/gurgaon_data/appartments.csv

data_divider:
  root_dir: artifacts/data_divider
  train_dir: artifacts/data_divider/train.csv
  test_dir: artifacts/data_divider/test.csv
  validation_dir: artifacts/data_divider/validation.csv
